name: pdfrx_custom_background_color
description: A custom fork of pdfrx with dynamic background color management. This package extends the original pdfrx with the ability to change PDF viewer background colors dynamically, including transparency support.
version: 2.1.3-custom.1
homepage: https://github.com/alx-code/pdfrx_custom_background_color
repository: https://github.com/alx-code/pdfrx_custom_background_color
issue_tracker: https://github.com/alx-code/pdfrx_custom_background_color/issues
screenshots:
  - description: 'Viewer example on Web with custom background colors'
    path: screenshot.jpg

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  pdfrx_engine: ^0.1.12
  collection:
  crypto: ^3.0.6
  ffi:
  flutter:
    sdk: flutter
  http:
  path:
  path_provider: ^2.1.5
  rxdart:
  synchronized: ^3.3.1
  url_launcher: ^6.3.1
  vector_math: ^2.1.4
  web: ^1.1.1
  dart_pubspec_licenses: ^3.0.4

dev_dependencies:
  ffigen: ^19.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  archive: ^4.0.7

flutter:
  plugin:
    platforms:
      web:
      # Deshabilitar plataformas nativas para que el plugin no compile en Android/iOS

  assets:
    - assets/
